name: Lumino Protocol CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci
  PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  RPC_URL: ${{ secrets.RPC_URL }}

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: forge install

      - name: Check contract sizes
        run: forge build --sizes
        id: build

      - name: Check gas snapshots
        run: forge snapshot --check
        id: snapshot

      - name: Run tests
        run: forge test -vvv
        id: test

      - name: Run coverage
        run: forge coverage --report lcov
        id: coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./lcov.info
          fail_ci_if_error: true

  slither:
    name: Slither Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Slither
        run: |
          python -m pip install --upgrade pip
          pip3 install slither-analyzer

      - name: Run Slither
        run: slither . --sarif slither.sarif || true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: slither.sarif

  lint:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Prettier and Solidity Plugin
        run: |
          npm install --save-dev prettier prettier-plugin-solidity

      - name: Check formatting
        run: npx prettier --check "src/**/*.sol" "test/**/*.sol"